[package]
name = "xact-mesut"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
mesut = { workspace = true }
mesut-observe = { workspace = true }
xact-process = { workspace = true }
xact-bank = { workspace = true }
xact-see = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
